version: "3.8"
services:
  app:
    build: 
      context: .
      target: dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:3000


networks:
  default:
    external:
      name: dev-network
